version: '3.8'

services:
  # --------------------------------------------------
  # Base de données PostgreSQL
  # --------------------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: my-service-db
    environment:
      POSTGRES_DB: myservicedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5435:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myservicedb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --------------------------------------------------
  # Serveur Keycloak
  # --------------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: myservice-keycloak
    command: start-dev --import-realm --insecure
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8085:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - keycloak_imports:/opt/keycloak/data/import
    networks:
      - app-network

  # --------------------------------------------------
  # Microservice Python gRPC (Chiffrement AES-GCM)
  # --------------------------------------------------
  my-service-crypto:
    build:
      context: ../my-service-crypto
      dockerfile: Dockerfile
    container_name: my-service-crypto
    environment:
      PYTHONUNBUFFERED: "1"
      GRPC_PORT: 50051
      CRYPTO_SECRET_KEY: "MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE="
    ports:
      - "50051:50051"
    networks:
      - app-network

  # --------------------------------------------------
  # Backend Spring Boot
  # --------------------------------------------------
  my-service-backend:
    build:
      context: ../my-service
      dockerfile: Dockerfile
    container_name: my-service-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myservicedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/my-realm
      GRPC_CLIENT_CRYPTO_HOST: my-service-crypto
      GRPC_CLIENT_CRYPTO_PORT: 50051
    ports:
      - "8082:8081"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      my-service-crypto:
        condition: service_started
    networks:
      - app-network

  # --------------------------------------------------
  # Frontend Angular + Nginx
  # --------------------------------------------------
  my-service-frontend:
    build:
      context: ../my-service-ui
      dockerfile: Dockerfile
    container_name: my-service-frontend
    ports:
      - "80:80"
    depends_on:
      - my-service-backend
    networks:
      - app-network

volumes:
  postgres_data:
  keycloak_data:
  keycloak_imports:

networks:
  app-network:
    driver: bridge

    # --------------------------------------------------
  # Microservice Cards (Spring Boot)
  # --------------------------------------------------
  my-service-cards:
    build:
      context: ../my-service-cards
      dockerfile: Dockerfile
    container_name: my-service-cards
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_cards_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/my-service-realm
      GRPC_CLIENT_CRYPTO_HOST: my-service-crypto
      GRPC_CLIENT_CRYPTO_PORT: 50051
    ports:
      - "8083:8081"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      my-service-crypto:
        condition: service_started
    networks:
      - app-network