version: '3.8'

services:
  # --------------------------------------------------
  # Base de données PostgreSQL
  # --------------------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: my-service-db
    environment:
      POSTGRES_DB: myservicedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myservicedb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --------------------------------------------------
  # Serveur Keycloak
  # --------------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: myservice-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      # - ./imports:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data
    networks:
      - app-network

  # --------------------------------------------------
  # Backend Spring Boot
  # --------------------------------------------------
  my-service-backend:
    build:
      context: ../my-service
      dockerfile: Dockerfile
    container_name: my-service-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myservicedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      # Configuration de l'Issuer Keycloak via le nom du service Docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/my-realm
    ports:
      - "8082:8081"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - app-network

  # --------------------------------------------------
  # Frontend Angular + Nginx
  # --------------------------------------------------
  my-service-frontend:
    build:
      context: ../my-service-ui
      dockerfile: Dockerfile
    container_name: my-service-frontend
    ports:
      - "80:80"
    depends_on:
      - my-service-backend
    networks:
      - app-network

volumes:
  postgres_data:
  keycloak_data:

networks:
  app-network:
    driver: bridge